/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_project;
import java.awt.Color;
import java.sql.*;
import java.awt.*;
/**
 *
 * @author michae29
 */
public class GenMed extends javax.swing.JFrame {

    /**
     * Creates new form GenMed
     */
    public GenMed() {
        initComponents();
        
    }
    public GenMed(Patient P1)
    {
        initComponents();
                
       
        PID.setText(Integer.toString(P1.getPID()));
        Fname.setText(P1.getFname());
        Lname.setText(P1.getLname());
        
        GenMedID.setText(P1.GetMedID());
        MaritalStatus.setText(P1.getStatus());
        
        
        Tobacco.setText(P1.getTobacco());
        TobQuantity.setText(P1.getTobQuan());
        TobDuration.setText(P1.getTobDur());
        
        Alcohol.setText(P1.getAlcho());
        AlcoholQuan.setText(P1.getAlchoQuan());
        AlcoholDur.setText(P1.getAlchoDur());
        
        Drug.setText(P1.getDrug());
        Drugtype.setText(P1.getDrugtype());
        Drugdur.setText(P1.getDrugDur());
        
        Bloodtype.setText(P1.getBlood());
        RHfactor.setText(P1.getRH());
        
        PID.setEditable(false);
        Fname.setEditable(false);
        Lname.setEditable(false);
        Alcohol.setEditable(false);
        AlcoholDur.setEditable(false);
        AlcoholQuan.setEditable(false);
        Bloodtype.setEditable(false);
        Drug.setEditable(false);
        Drugdur.setEditable(false);
        Drugtype.setEditable(false);
        Fname.setEditable(false);
        GenMedID.setEditable(false);
        Lname.setEditable(false);
        MaritalStatus.setEditable(false);
        PID.setEditable(false);
        RHfactor.setEditable(false);
        TobDuration.setEditable(false);
        TobQuantity.setEditable(false);
        Tobacco.setEditable(false);
        
        PID.setBackground(Color.lightGray);
        Fname.setBackground(Color.lightGray);
        Lname.setBackground(Color.lightGray);
        Alcohol.setBackground(Color.lightGray);
        AlcoholDur.setBackground(Color.lightGray);
        AlcoholQuan.setBackground(Color.lightGray);
        Bloodtype.setBackground(Color.lightGray);
        Drug.setBackground(Color.lightGray);
        Drugdur.setBackground(Color.lightGray);
        Drugtype.setBackground(Color.lightGray);
        Fname.setBackground(Color.lightGray);
        GenMedID.setBackground(Color.lightGray);
        Lname.setBackground(Color.lightGray);
        MaritalStatus.setBackground(Color.lightGray);
        PID.setBackground(Color.lightGray);
        RHfactor.setBackground(Color.lightGray);
        TobDuration.setBackground(Color.lightGray);
        TobQuantity.setBackground(Color.lightGray);
        Tobacco.setBackground(Color.lightGray);
        
        
        Save.setVisible(false);
        Save2.setVisible(false);
        Delete.setVisible(false);
        New.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Return = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        New = new javax.swing.JButton();
        Save2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        GenMedID = new javax.swing.JTextField();
        MaritalStatus = new javax.swing.JTextField();
        Tobacco = new javax.swing.JTextField();
        TobQuantity = new javax.swing.JTextField();
        TobDuration = new javax.swing.JTextField();
        Alcohol = new javax.swing.JTextField();
        AlcoholQuan = new javax.swing.JTextField();
        AlcoholDur = new javax.swing.JTextField();
        Drug = new javax.swing.JTextField();
        Drugtype = new javax.swing.JTextField();
        Drugdur = new javax.swing.JTextField();
        Bloodtype = new javax.swing.JTextField();
        RHfactor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PID = new javax.swing.JTextField();
        Fname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Return.setText("Return");
        Return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnMouseClicked(evt);
            }
        });
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        Edit.setText("Edit");
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 66, -1));

        Save.setText("Save");
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 66, -1));

        Delete.setText("Delete");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        New.setText("New");
        New.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewMouseClicked(evt);
            }
        });
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        getContentPane().add(New, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 66, -1));

        Save2.setText("New Patient");
        Save2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Save2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Save2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Save2MouseClicked(evt);
            }
        });
        Save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save2ActionPerformed(evt);
            }
        });
        getContentPane().add(Save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GenMedID.setText("jTextField2");
        jPanel2.add(GenMedID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        MaritalStatus.setText("jTextField2");
        jPanel2.add(MaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        Tobacco.setText("jTextField2");
        jPanel2.add(Tobacco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        TobQuantity.setText("jTextField2");
        jPanel2.add(TobQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        TobDuration.setText("jTextField2");
        jPanel2.add(TobDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        Alcohol.setText("jTextField2");
        jPanel2.add(Alcohol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        AlcoholQuan.setText("jTextField2");
        jPanel2.add(AlcoholQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        AlcoholDur.setText("jTextField2");
        jPanel2.add(AlcoholDur, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        Drug.setText("jTextField2");
        jPanel2.add(Drug, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        Drugtype.setText("jTextField2");
        jPanel2.add(Drugtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        Drugdur.setText("jTextField2");
        jPanel2.add(Drugdur, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        Bloodtype.setText("jTextField2");
        jPanel2.add(Bloodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        RHfactor.setText("jTextField2");
        jPanel2.add(RHfactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel3.setText("Medical ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setText("Marital Status");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel5.setText("Tobacco");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel6.setText("Quantity");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel7.setText("Duration");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel8.setText("Alcohol");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jLabel9.setText("Quantity");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel10.setText("Duration");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel11.setText("Drug");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel12.setText("Type");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel13.setText("Duration");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel14.setText("Blood Type");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel15.setText("RH factor");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel1.setText("Return to Main");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 320, 340));

        PID.setText("Patient ID");
        PID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIDActionPerformed(evt);
            }
        });

        Fname.setText("Patient First Name");
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });

        Lname.setText("Patient Last Name");
        Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(PID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 420, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnMouseClicked
        this.hide();
        New_Main MP = new New_Main();
        MP.setVisible(true);
    }//GEN-LAST:event_ReturnMouseClicked

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewActionPerformed

    private void NewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMouseClicked

        
        
        
        Fname.setText("");
        Lname.setText("");
        Alcohol.setText("");
        AlcoholDur.setText("");
        AlcoholQuan.setText("");
        Bloodtype.setText("");
        Drug.setText("");
        Drugdur.setText("");
        Drugtype.setText("");
        Fname.setText("");
        Lname.setText("");
        MaritalStatus.setText("");
        RHfactor.setText("");
        TobDuration.setText("");
        TobQuantity.setText("");
        Tobacco.setText("");  
        
        Fname.setPreferredSize(new Dimension(73, 24));
        Lname.setPreferredSize(new Dimension(73, 24));
        Alcohol.setPreferredSize(new Dimension(73, 24));
        AlcoholDur.setPreferredSize(new Dimension(73, 24));
        AlcoholQuan.setPreferredSize(new Dimension(73, 24));
        Bloodtype.setPreferredSize(new Dimension(73, 24));
        Drug.setPreferredSize(new Dimension(73, 24));
        Drugdur.setPreferredSize(new Dimension(73, 24));
        Drugtype.setPreferredSize(new Dimension(73, 24));
        Fname.setPreferredSize(new Dimension(73, 24));
        Lname.setPreferredSize(new Dimension(73, 24));
        MaritalStatus.setPreferredSize(new Dimension(73, 24));
        RHfactor.setPreferredSize(new Dimension(73, 24));
        TobDuration.setPreferredSize(new Dimension(73, 24));
        TobQuantity.setPreferredSize(new Dimension(73, 24));
        Tobacco.setPreferredSize(new Dimension(73, 24));  
         
         
    }//GEN-LAST:event_NewMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        Patient p1 = new Patient();
        
        p1.DeleteData(Integer.parseInt(PID.getText()),GenMedID.getText());
        
        
        Save.setVisible(false);
        Delete.setVisible(false);
        New.setVisible(false);
        Save2.setVisible(false);
        
        PID.setBackground(Color.lightGray);
        Fname.setBackground(Color.lightGray);
        Lname.setBackground(Color.lightGray);

    }//GEN-LAST:event_DeleteMouseClicked

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
        Patient p1 = new Patient();
        
        p1.UpdateData(Integer.parseInt(PID.getText()), Fname.getText(), Lname.getText(),
        
        
       MaritalStatus.getText(),
       Tobacco.getText(),
       TobQuantity.getText(),
       TobDuration.getText(),
       Alcohol.getText(),
       AlcoholQuan.getText(),
       AlcoholDur.getText(),
       Drug.getText(),
       Drugtype.getText(),
       Drugdur.getText(),
       Bloodtype.getText(),
       RHfactor.getText(), 
       GenMedID.getText()
        );
        
        PID.setEditable(false);
        Fname.setEditable(false);
        Lname.setEditable(false);
        Alcohol.setEditable(false);
        AlcoholDur.setEditable(false);
        AlcoholQuan.setEditable(false);
        Bloodtype.setEditable(false);
        Drug.setEditable(false);
        Drugdur.setEditable(false);
        Drugtype.setEditable(false);
        Fname.setEditable(false);
        GenMedID.setEditable(false);
        Lname.setEditable(false);
        MaritalStatus.setEditable(false);
        RHfactor.setEditable(false);
        TobDuration.setEditable(false);
        TobQuantity.setEditable(false);
        Tobacco.setEditable(false);
        
        PID.setBackground(Color.lightGray);
        Fname.setBackground(Color.lightGray);
        Lname.setBackground(Color.lightGray);
        Alcohol.setBackground(Color.lightGray);
        AlcoholDur.setBackground(Color.lightGray);
        AlcoholQuan.setBackground(Color.lightGray);
        Bloodtype.setBackground(Color.lightGray);
        Drug.setBackground(Color.lightGray);
        Drugdur.setBackground(Color.lightGray);
        Drugtype.setBackground(Color.lightGray);
        Fname.setBackground(Color.lightGray);
        GenMedID.setBackground(Color.lightGray);
        Lname.setBackground(Color.lightGray);
        MaritalStatus.setBackground(Color.lightGray);
        PID.setBackground(Color.lightGray);
        RHfactor.setBackground(Color.lightGray);
        TobDuration.setBackground(Color.lightGray);
        TobQuantity.setBackground(Color.lightGray);
        Tobacco.setBackground(Color.lightGray);
        
        Save.setVisible(false);
        Delete.setVisible(false);
        New.setVisible(false);
        Save2.setVisible(false);
        
    }//GEN-LAST:event_SaveMouseClicked

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
     
        Fname.setEditable(true);
        Lname.setEditable(true);
        Alcohol.setEditable(true);
        AlcoholDur.setEditable(true);
        AlcoholQuan.setEditable(true);
        Bloodtype.setEditable(true);
        Drug.setEditable(true);
        Drugdur.setEditable(true);
        Drugtype.setEditable(true);
        MaritalStatus.setEditable(true);
        RHfactor.setEditable(true);
        TobDuration.setEditable(true);
        TobQuantity.setEditable(true);
        Tobacco.setEditable(true);
        
        Fname.setBackground(Color.white);
        Lname.setBackground(Color.white);
        Alcohol.setBackground(Color.white);
        AlcoholDur.setBackground(Color.white);
        AlcoholQuan.setBackground(Color.white);
        Bloodtype.setBackground(Color.white);
        Drug.setBackground(Color.white);
        Drugdur.setBackground(Color.white);
        Drugtype.setBackground(Color.white);
        MaritalStatus.setBackground(Color.white);
        RHfactor.setBackground(Color.white);
        TobDuration.setBackground(Color.white);
        TobQuantity.setBackground(Color.white);
        Tobacco.setBackground(Color.white);
        
        Save.setVisible(true);
        Save2.setVisible(true);
        Delete.setVisible(true);
        New.setVisible(true);
      
        
    }//GEN-LAST:event_EditMouseClicked

    private void Save2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Save2MouseClicked
       
        Patient p1 = new Patient();
        
        p1.InsertData(Fname.getText(), Lname.getText(),
                MaritalStatus.getText(),
       Tobacco.getText(),
       TobQuantity.getText(),
       TobDuration.getText(),
       Alcohol.getText(),
       AlcoholQuan.getText(),
       AlcoholDur.getText(),
       Drug.getText(),
       Drugtype.getText(),
       Drugdur.getText(),
       Bloodtype.getText(),
       RHfactor.getText(), 
       GenMedID.getText());
                
        
        Save.setVisible(false);
        Delete.setVisible(false);
        New.setVisible(false);
        Save2.setVisible(false);
        
       PID.setEditable(false);
        Fname.setEditable(false);
        Lname.setEditable(false);
        Alcohol.setEditable(false);
        AlcoholDur.setEditable(false);
        AlcoholQuan.setEditable(false);
        Bloodtype.setEditable(false);
        Drug.setEditable(false);
        Drugdur.setEditable(false);
        Drugtype.setEditable(false);
        Fname.setEditable(false);
        GenMedID.setEditable(false);
        Lname.setEditable(false);
        MaritalStatus.setEditable(false);
        PID.setEditable(false);
        RHfactor.setEditable(false);
        TobDuration.setEditable(false);
        TobQuantity.setEditable(false);
        Tobacco.setEditable(false);
        
        PID.setBackground(Color.lightGray);
        Fname.setBackground(Color.lightGray);
        Lname.setBackground(Color.lightGray);
        Alcohol.setBackground(Color.lightGray);
        AlcoholDur.setBackground(Color.lightGray);
        AlcoholQuan.setBackground(Color.lightGray);
        Bloodtype.setBackground(Color.lightGray);
        Drug.setBackground(Color.lightGray);
        Drugdur.setBackground(Color.lightGray);
        Drugtype.setBackground(Color.lightGray);
        Fname.setBackground(Color.lightGray);
        GenMedID.setBackground(Color.lightGray);
        Lname.setBackground(Color.lightGray);
        MaritalStatus.setBackground(Color.lightGray);
        PID.setBackground(Color.lightGray);
        RHfactor.setBackground(Color.lightGray);
        TobDuration.setBackground(Color.lightGray);
        TobQuantity.setBackground(Color.lightGray);
        Tobacco.setBackground(Color.lightGray);
    }//GEN-LAST:event_Save2MouseClicked

    private void LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameActionPerformed

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameActionPerformed

    private void PIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIDActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnActionPerformed

    private void Save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Save2ActionPerformed

/*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alcohol;
    private javax.swing.JTextField AlcoholDur;
    private javax.swing.JTextField AlcoholQuan;
    private javax.swing.JTextField Bloodtype;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Drug;
    private javax.swing.JTextField Drugdur;
    private javax.swing.JTextField Drugtype;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField GenMedID;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField MaritalStatus;
    private javax.swing.JButton New;
    private javax.swing.JTextField PID;
    private javax.swing.JTextField RHfactor;
    private javax.swing.JButton Return;
    private javax.swing.JButton Save;
    private javax.swing.JButton Save2;
    private javax.swing.JTextField TobDuration;
    private javax.swing.JTextField TobQuantity;
    private javax.swing.JTextField Tobacco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
